import os
from dotenv import load_dotenv
load_dotenv()

WL_VENDORID = os.getenv("WL_VENDORID")
WL_APIKEY = os.getenv("WL_APIKEY")
WL_LASTTRANSACTIONID_FILE = 'wl_lastTransactionID.txt'

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
DISCORD_WEBHOOK_MAX_EMBEDS_PER_MESSAGE = 10
DISCORD_EMBED_COLOR_WITHDRAWAL = 15158332
DISCORD_EMBED_COLOR_PURCHASE = 3066993
